name: learnmate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain==0.3.24
      - langchain-community==0.3.22
      - langchain-core==0.3.55
      - langchain-openai==0.3.14
      - langchain-huggingface==0.1.2
      - huggingface-hub==0.30.2
      - sentence-transformers==4.1.0
      - openai==1.74.0
      - faiss-cpu==1.7.4
      - pydantic==2.11.3
      - pydantic-settings==2.9.1
      - python-dotenv==1.1.0
      - streamlit==1.44.1
      - unstructured==0.17.2
      - pandas
      - numpy
      - tqdm
      - requests
      - pdfplumber
      - PyPDF2
      - tiktoken
